# Generated by Django 2.2.2 on 2019-06-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='job',
            table='Job',
        ),
    ]
