# Generated by Django 2.2.2 on 2019-06-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='images/blog')),
            ],
            options={
                'db_table': 'Blog',
            },
        ),
    ]
